/**
 * Downloads what the /hq panel manages (markets, pages, updates, testimonials,
 * team, certifications) and writes it to src/data/remote.generated.js, which
 * the site's data files read when the site is built.
 *
 * It runs before every build/dev/lint/smoke (see the "pre…" scripts in
 * package.json). It must never break a build: if there is no API address, the
 * API is down, or it returns nothing, the file is written empty and the site
 * builds from its built-in data (the 26 markets in data/markets.js).
 *
 * The file is git-ignored, so building never leaves the working tree dirty.
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEnv } from 'vite';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const out = path.join(root, 'src/data/remote.generated.js');

const mode = process.env.NODE_ENV === 'development' ? 'development' : 'production';
const env = { ...loadEnv(mode, root, 'VITE_'), ...process.env };
const base = (env.VITE_API_URL || '').replace(/\/$/, '');

const KEYS = ['markets', 'hiddenMarkets', 'pages', 'updates', 'testimonials', 'team', 'certifications'];
let data = {};
let note = 'no VITE_API_URL — using built-in data';

if (base) {
  try {
    const res = await fetch(`${base}/api/public/content`, {
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const json = await res.json();
    for (const k of KEYS) if (Array.isArray(json[k])) data[k] = json[k];
    note = `from ${base}: ${KEYS.map((k) => `${k} ${data[k]?.length ?? 0}`).join(', ')}`;
  } catch (err) {
    note = `could not reach ${base} (${err.message}) — using built-in data`;
  }
}

await writeFile(
  out,
  `// Generated by scripts/fetch-content.mjs — do not edit, do not commit.\n` +
    `export default ${JSON.stringify(data, null, 2)};\n`
);
console.log(`[content] ${note}`);
